/* Generated by scripts/gen-colors.mjs. Do not edit.
 *
 * The colour values themselves live in src/styles/colors.generated.css, as CSS
 * custom properties, so that a theme change repaints without JavaScript. This
 * module only carries the sizes the runtime must know.
 */
export const SEQ_STOPS = 10;
export const DIV_STOPS = 4;
export const CAT_STOPS = 8;
