/**
 * Generates the colour tables of react-dsfr-chart.
 *
 * chroma-js is a DEV dependency: every colour derivation of @gouvfr/dsfr-chart
 * (darken(0.8), brighten(0.5), chroma.scale(...).colors(n)) is evaluated here,
 * at build time, and written out as static values. Nothing of chroma-js reaches
 * the published bundle.
 *
 * Outputs:
 *   src/styles/colors.generated.css  the CSS custom properties, light + dark.
 *                                    Values live in CSS so that switching
 *                                    `data-fr-theme` costs no JavaScript.
 *   src/core/colors.generated.ts     the few constants the runtime needs.
 *   tests/fixtures/colors.json       the same values, for the parity test.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import chroma from 'chroma-js';
import source from './dsfr-colors.json' with { type: 'json' };

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const THEMES = ['light', 'dark'];

/**
 * The tokens a chart names directly. `colors.json` holds fifteen numbered
 * tokens, but only the first eight are a palette: 09 and 10 are the ends of
 * the sequential scale, 11, 13 and 15 the stops of the divergent one, and 12
 * and 14 are unused. Those seven feed the scales below and never reach the
 * stylesheet, so the stylesheet carries no colour a chart cannot ask for.
 */
const TOKENS = [
  ...Array.from({ length: 8 }, (_, i) => String(i + 1).padStart(2, '0')),
  'default',
  'neutral',
];

export const SEQ_STOPS = 10;
export const DIV_STOPS = 4;

const token = (theme, name) => source[theme][`dsfr-chart-colors-${name}`];
const darken = (hex) => chroma(hex).darken(0.8).hex();
const brighten = (hex) => chroma(hex).brighten(0.5).hex();

/** `getSequentialAscending()` of src/utils/colors.js. */
const sequential = (theme) => chroma.scale([token(theme, '09'), token(theme, '10')]).colors(SEQ_STOPS);
/** `getDivergentAscending()` of src/utils/colors.js. */
const divergent = (theme) => chroma.scale([token(theme, '11'), token(theme, '13'), token(theme, '15')]).colors(DIV_STOPS);

// The library reverses the ascending scale to obtain the descending one, which
// is only correct because both scales are symmetric. Verify, do not assume.
for (const theme of THEMES) {
  const pairs = [
    [sequential(theme).slice().reverse(), chroma.scale([token(theme, '10'), token(theme, '09')]).colors(SEQ_STOPS)],
    [divergent(theme).slice().reverse(), chroma.scale([token(theme, '15'), token(theme, '13'), token(theme, '11')]).colors(DIV_STOPS)],
  ];
  for (const [reversed, upstream] of pairs) {
    if (reversed.join() !== upstream.join()) {
      throw new Error(`The descending scale of the "${theme}" theme is not the reverse of the ascending one.`);
    }
  }
}

const values = {};
for (const theme of THEMES) {
  const vars = {};
  for (const name of TOKENS) {
    const hex = token(theme, name);
    vars[`--rdc-${name}`] = hex;
    vars[`--rdc-${name}-dk`] = darken(hex);
    // The line chart brightens on hover where the pie and the bar darken.
    vars[`--rdc-${name}-br`] = brighten(hex);
  }
  // Both scales carry the two hover variants: the pie and the bar darken a stop,
  // the line chart brightens it, and `choosePalette` hands them the same names.
  sequential(theme).forEach((hex, i) => {
    vars[`--rdc-seq-${i}`] = hex;
    vars[`--rdc-seq-${i}-dk`] = darken(hex);
    vars[`--rdc-seq-${i}-br`] = brighten(hex);
  });
  divergent(theme).forEach((hex, i) => {
    vars[`--rdc-div-${i}`] = hex;
    vars[`--rdc-div-${i}-dk`] = darken(hex);
    vars[`--rdc-div-${i}-br`] = brighten(hex);
  });
  values[theme] = vars;
}

const block = (selector, vars) => `${selector} {\n${Object.entries(vars)
  .map(([k, hex]) => `  ${k}: ${hex};`)
  .join('\n')}\n}`;

const css = `/* Generated by scripts/gen-colors.mjs. Do not edit. */
${block(':root', values.light)}

${block('[data-fr-theme="dark"]', values.dark)}
`;

const ts = `/* Generated by scripts/gen-colors.mjs. Do not edit.
 *
 * The colour values themselves live in src/styles/colors.generated.css, as CSS
 * custom properties, so that a theme change repaints without JavaScript. This
 * module only carries the sizes the runtime must know.
 */
export const SEQ_STOPS = ${SEQ_STOPS};
export const DIV_STOPS = ${DIV_STOPS};
export const CAT_STOPS = 8;
`;

mkdirSync(join(root, 'src/styles'), { recursive: true });
mkdirSync(join(root, 'src/core'), { recursive: true });
mkdirSync(join(root, 'tests/fixtures'), { recursive: true });
writeFileSync(join(root, 'src/styles/colors.generated.css'), css);
writeFileSync(join(root, 'src/core/colors.generated.ts'), ts);
writeFileSync(join(root, 'tests/fixtures/colors.json'), JSON.stringify(values, null, 2) + '\n');

console.log(`Wrote ${Object.keys(values.light).length} custom properties per theme.`);
